// Catálogo de ejemplo / estructura para productos afiliados.
// IMPORTANTE: sustituye los datos de ejemplo por productos reales y enlaces
// generados desde Awin Link Builder antes de publicar una versión comercial.

export const products = [
  { id: 1, name: "Mueble de baño suspendido", category: "banos", store: "Leroy Merlin", description: "Solución de almacenaje para renovar un baño y aprovechar mejor el espacio.", price: null, oldPrice: null, discount: null, badge: "Selección", image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 2, name: "Grifo monomando de cocina", category: "cocinas", store: "Leroy Merlin", description: "Una opción práctica para renovar la zona de fregadero de la cocina.", price: null, oldPrice: null, discount: null, badge: "Selección", image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 3, name: "Taladro inalámbrico 18V", category: "herramientas", store: "Tienda colaboradora", description: "Herramienta versátil para pequeños trabajos de montaje y mantenimiento.", price: null, oldPrice: null, discount: null, badge: "Herramienta", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 4, name: "Lámpara colgante moderna", category: "decoracion", store: "Tienda colaboradora", description: "Idea de iluminación decorativa para comedor, cocina o zona de estar.", price: null, oldPrice: null, discount: null, badge: "Decoración", image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 5, name: "Set de muebles para jardín", category: "jardin", store: "Tienda colaboradora", description: "Conjunto para crear una zona exterior cómoda y funcional.", price: null, oldPrice: null, discount: null, badge: "Exterior", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 6, name: "Pintura interior lavable", category: "pintura", store: "Tienda colaboradora", description: "Alternativa para renovar paredes y cambiar el aspecto de una estancia.", price: null, oldPrice: null, discount: null, badge: "Reforma", image: "https://images.unsplash.com/photo-1562259949-e8e7684d7828?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 7, name: "Espejo redondo para baño", category: "banos", store: "Tienda colaboradora", description: "Elemento decorativo y funcional para completar una reforma de baño.", price: null, oldPrice: null, discount: null, badge: "Baño", image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" },
  { id: 8, name: "Organizador modular de herramientas", category: "herramientas", store: "Tienda colaboradora", description: "Para mantener ordenadas herramientas y accesorios de trabajo.", price: null, oldPrice: null, discount: null, badge: "Organización", image: "https://images.unsplash.com/photo-1581147036324-c17ac41f4b55?auto=format&fit=crop&w=900&q=80", affiliateUrl: "https://www.awin1.com/cread.php?s=TU_ENLACE_AWIN&awinmid=TU_ID" }
];
